### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mehaase** [HyperionGray/python-chrome-devtools-protocol#10]
The docs have a few drawbacks right now:

* The modules are hardcoded in `api.rst`. So if we use a new CDP spec that has a different set of domains, the old domains won't be removed and the new domains won't be added. We should generate the module list automatically.
* The sphinx build has a bunch of errors that need to be fixed.
* Type annotations aren't used in the docs. I tried using an annotations extension for Sphinx but it seemed to conflict with autodoc and I didn't have time to figure it out.
* The API page is so huge that it takes a while to download and render. It might be more helpful to create separate pages for each domain?

**Comment by mehaase** [comment]
A couple other things:

* The description of each domain is not included in the generated python code.
* But the python docblocks do contain the "this is generated code" warning, which shows up in the documentation. This warning should be placed into comments, not the docstring.

**Comment by mehaase** [comment]
More:

* (Related to the annotations issue above) Types (e.g. parameters to methods) are not hyperlinked, so you have to search the page to find the matching type definition.
* Enumeration values are not displayed. This is extremely unhelpful.
* I'd like to have each CDP module listed in the table of contents on the left side, since this would make it much faster to find items relevant to a particular CDP domain.
* I'd also like to organize each CDP by commands, events, and types.

The last 2 items suggest that the generator script also needs to generate some sphinx documents.

**Comment by mehaase** [comment]
* The module index (linked from index.rst) is pretty useless. We only have a single, top-level package, and displaying the modules in the sidebar would be much better.
* The search.html link in index.rst is also useless. It goes to empty search results.

**Comment by mehaase** [comment]
Dom made some progress in #14.

**Comment by auphofBSF** [comment]
Excellent module, thank you, I would like that the return values of a call to a domain function like `dom.perform_search' in a  pythonic form. like a object from the json dict not a tuple. 
I see in the generator https://github.com/HyperionGray/python-chrome-devtools-protocol/blob/8081739e6b7b875fa4d6c95852036c32c4668ea1/generator/generate.py#L606 there is support for generated function to return a generated object based on the cdp json if self.result = 1. It is not immediate apparent how I could run the generator to create the cdp folder with this option set. Would appreciate if this could be pointed out, Thank you

**Comment by mehaase** [comment]
If the CDP function is defined to return a single item, then we do return a Python wrapper type. For example, `dom.query_selector(...)` returns a `NodeId` object.

As you've noticed, `dom.perform_search()` is a multi-return function. Unfortunately, CDP does not define formal types for multi-return functions, so there's no specific type to return. We could return an `object` (like lines 7-8 in your example) but that doesn't provide any useful type hints and it requires the caller to take an extra step to "unpack" any values they want to use. In an earlier version of the library, these functions returned a dictionary (like lines 9-10 of your example), but this has the same drawbacks as using `object`: lack of type hints and the need for the caller to unpack the result.

Our recommendation is to use tuple unpacking:

```python
search_id, result_count = await session.execute(
    dom.perform_search(query=xpath_query)
)
```

This preserves type hints for `search_id` and `result_count` and also doesn't require a separate unpacking step. For unwanted return values, we use the convention of unpacking into a dummy underscore variable. For example, if we don't want result count, we would write `search_id, _ = await session.execute(...)`.

**Comment by auphofBSF** [comment]
> If the CDP function is defined to return a single item, then we do return a Python wrapper type. For example, `dom.query_selector(...)` returns a `NodeId` object.
> 
> As you've noticed, `dom.perform_search()` is a multi-return function. Unfortunately, CDP does not define formal types for multi-return functions, so there's no specific type to return. We could return an `object` (like lines 7-8 in your example) but that doesn't provide any useful type hints and it requires the caller to take an extra step to "unpack" any values they want to use. In an earlier version of the library, these functions returned a dictionary (like lines 9-10 of your example), but this has the same drawbacks as using `object`: lack of type hints and the need for the caller to unpack the result.
> 
> Our recommendation is to use tuple unpacking:

Sounds like a fair and appropriate  immediate work around

> 
> ```python
> search_id, result_count = await session.execute(
>     dom.perform_search(query=xpath_query)
> )
> ```
> 
> This preserves type hints for `search_id` and `result_count` and also doesn't require a separate unpacking step. For unwanted return values, we use the convention of unpacking into a dummy underscore variable. For example, if we don't want result count, we would write `search_id, _ = await session.execute(...)`.

In looking. (admit tingly  my first look) at the https://github.com/HyperionGray/python-chrome-devtools-protocol/blob/8081739e6b7b875fa4d6c95852036c32c4668ea1/generator/browser_protocol.json#L3863 it appears that all returns are well defined, I can also see some complications of multiple return values, but a good majority of functions could have a defined Returned type `@dataclass` generated for there return value. Would this be a fair and possible New Feature/enhancement. Thank you for your consideration and appropriate immediate work around

**Comment by mehaase** [comment]
> …but a good majority of functions could have a defined Returned type `@dataclass` generated for there return value. 

I think I'm either misunderstanding you or you are misunderstanding me. All of the single-return functions in CDP already return an instance of a dataclass type. For example, [`target.get_target_info(...)`](https://py-cdp.readthedocs.io/en/latest/api.html#cdp.target.get_target_info) returns a [`TargetInfo`](https://py-cdp.readthedocs.io/en/latest/api.html#cdp.target.TargetInfo) instance, which is itself a dataclass.

**Comment by auphofBSF** [comment]
> > …but a good majority of functions could have a defined Returned type `@dataclass` generated for there return value.
> 
> I think I'm either misunderstanding you or you are misunderstanding me. All of the single-return functions in CDP already return an instance of a dataclass type. For example, [`target.get_target_info(...)`](https://py-cdp.readthedocs.io/en/latest/api.html#cdp.target.get_target_info) returns a [`TargetInfo`](https://py-cdp.readthedocs.io/en/latest/api.html#cdp.target.TargetInfo) instance, which is itself a dataclass.

I appreciate all the single return functions do return a dataclass type. I am specifically looking at functions that return multiple items, I envisage a dataclass for return values of those functions. ie.
`dom.perform_search(...) -> dom.perform_search_returns` this `dom.perform_search_returns is a generated dataclass with attributes `search_id` and `result_count`.   This will make these multiple return values consistent with the single returns, everything returns a dataclass, for all the good reasons one uses dataclass's

In a brief analysis of the Page and DOM domain, all multiple returns are fixed, no optional or conditional return values. But I don't have extensive CDP experience to be 100% sure.

A quick analysis in the `Page` domain of the 16 commands with returns, 6 of these have multiple returns, for the `DOM` domain of the 23 commands with returns only 3 have multiple returns. 

> 
> The main problem right now is that the generated documentation doesn't do a great job showing what the return type is. But that will be addressed by this issue eventually. If you want to submit a PR to improve the documentation, that would be great!

I will look into it a bit further, and checkout your recent commits. 

Thank you for the great set of  modules ,python-chrome-devtools-protocol, 
trio-chrome-devtools-protocol. Your input and responses and efforts in Jupyter support for trio in IPython and IPyKernel etc

**Comment by mehaase** [comment]
This is pretty much done, but I'll leave the ticket open for a few days in case anybody wants to review the documentation before I close this issue.

There is [a bug in Python 3.7.5 and 3.8.0](https://bugs.python.org/issue34776) that breaks type hints on dataclasses, so some warnings are produced during docs build and the resulting documentation may not produce the correct hyperlinks. I'm not opening a separate issue in this repo since the bug is in Python itself and should be resolved in the near future.

**Comment by auphofBSF** [comment]
I have retrieved your latest commit f4525a7746704f5ec2dae16ae2dff66f57699324 and `cdp` is working in my initial brief tests with `trio_cpd`, but not tested examples or run tests in `trio_cpd`

As per your `docs/changelog.rst`  Had  to change  domain and types that conflict with builtins ie.  `input_`  and 'type_' , I imagine this may have some effect in examples or doc's in `trio_cpd`

**Should the version number be bumped up**, this is some significant changes ?

I wonder about including a simple `cpd.__version__`  attribute  and possibly a version of  the 
 `browse_protocol.json` https://github.com/HyperionGray/python-chrome-devtools-protocol/blob/f4525a7746704f5ec2dae16ae2dff66f57699324/generator/browser_protocol.json#L2

I am however retrieving the version of this module by  

``` python
import pip
pip.get_installed_distributions()
version('chrome-devtools-protocol')
```

The Documentation navigates well on https://py-cdp.readthedocs.io/en/latest/overview.html, 

My comments on alternatives to returning tuples as last  discussed in https://github.com/HyperionGray/python-chrome-devtools-protocol/issues/10#issuecomment-593023332  are certainly meant as an enhancement and have no relevance to closing this issue. 
Thank you

**Comment by mehaase** [comment]
Thanks @auphofBSF. I tagged a release 0.3.0 containing all of these changes on March 2nd. It's available on PyPI.
