### ISSUE TITLE
Handle deprecations

### ISSUE THREAD

**Issue by mehaase** [HyperionGray/python-chrome-devtools-protocol#4]
Some areas (domains, fields, etc.) are marked as deprecated. How should we handle these in our generated code? Here are two possibilities?

* Generate documentation showing that something is deprecated.
* Display deprecation warnings using python's warning system

**Comment by domderen** [comment]
This issue can be closed now, since this was merged: https://github.com/HyperionGray/python-chrome-devtools-protocol/commit/8081739e6b7b875fa4d6c95852036c32c4668ea1
